service: email-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: google
  runtime: python38
  project: lone-461009
  credentials: C:\Users\gugul\Downloads\Serverless_project_new\email-api\lone-461009-06de97721e9a.json
  region: us-central1
  environment:
    SENDER_EMAIL: ${env:SENDER_EMAIL}
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  sendEmail:
    handler: send_email
    events:
      - http: /send

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!ui/**'
    - '!ui/node_modules/**'
    - '*.py'